export interface Entreprises {
 _id:string;
 societe:string;
 commercial:string;
 siren:string;
 siret:string;
 juridique:string;
 tva:string;
 activite:string;
 pays:string;
 adresse:string;
 ville:string;
 rue:string;
 postal:string;
 site:string;
 email:string;
 indicatif:string;
 telephone:string;
 photo:string;
 corps_act:string;
 corps_etat:string;
 fournisseur:string;
 nom:string;
 prenom:string;
 numero:string;
 nbr_projet:string;
}
